#include "../kernels.h"

#include <cstdint>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <adf.h>
#include <aie_api/aie.hpp>
#include "aie_api/aie_types.hpp"
#include <adf.h>
#include <cstddef>
#include <cstdint>

namespace {

alignas(32) static const uint32_t K[64] = {
    0x428a2f98U, 0x71374491U, 0xb5c0fbcfU, 0xe9b5dba5U,
    0x3956c25bU, 0x59f111f1U, 0x923f82a4U, 0xab1c5ed5U,
    0xd807aa98U, 0x12835b01U, 0x243185beU, 0x550c7dc3U,
    0x72be5d74U, 0x80deb1feU, 0x9bdc06a7U, 0xc19bf174U,
    0xe49b69c1U, 0xefbe4786U, 0x0fc19dc6U, 0x240ca1ccU,
    0x2de92c6fU, 0x4a7484aaU, 0x5cb0a9dcU, 0x76f988daU,
    0x983e5152U, 0xa831c66dU, 0xb00327c8U, 0xbf597fc7U,
    0xc6e00bf3U, 0xd5a79147U, 0x06ca6351U, 0x14292967U,
    0x27b70a85U, 0x2e1b2138U, 0x4d2c6dfcU, 0x53380d13U,
    0x650a7354U, 0x766a0abbU, 0x81c2c92eU, 0x92722c85U,
    0xa2bfe8a1U, 0xa81a664bU, 0xc24b8b70U, 0xc76c51a3U,
    0xd192e819U, 0xd6990624U, 0xf40e3585U, 0x106aa070U,
    0x19a4c116U, 0x1e376c08U, 0x2748774cU, 0x34b0bcb5U,
    0x391c0cb3U, 0x4ed8aa4aU, 0x5b9cca4fU, 0x682e6ff3U,
    0x748f82eeU, 0x78a5636fU, 0x84c87814U, 0x8cc70208U,
    0x90befffaU, 0xa4506cebU, 0xbef9a3f7U, 0xc67178f2U
};

/*
 * Same constant previously generated by thash_f:
 *
 *     00 ... 00 03 00 00 00
 */
alignas(32) static const uint32_t PRF_PREFIX[8] = {
    0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0x00000003U
};

static inline uint32_t rotr32(uint32_t x, unsigned int n)
{
    return (x >> n) | (x << (32U - n));
}

static inline uint32_t big_sigma0(uint32_t x)
{
    return rotr32(x, 2) ^
           rotr32(x, 13) ^
           rotr32(x, 22);
}

static inline uint32_t big_sigma1(uint32_t x)
{
    return rotr32(x, 6) ^
           rotr32(x, 11) ^
           rotr32(x, 25);
}

static inline uint32_t small_sigma0(uint32_t x)
{
    return rotr32(x, 7) ^
           rotr32(x, 18) ^
           (x >> 3);
}

static inline uint32_t small_sigma1(uint32_t x)
{
    return rotr32(x, 17) ^
           rotr32(x, 19) ^
           (x >> 10);
}

static inline uint32_t choose(
    uint32_t x,
    uint32_t y,
    uint32_t z)
{
    return z ^ (x & (y ^ z));
}

static inline uint32_t majority(
    uint32_t x,
    uint32_t y,
    uint32_t z)
{
    return (x & y) ^ (z & (x ^ y));
}

static inline uint32_t swap32(uint32_t x)
{
    return __builtin_bswap32(x);
}

// static inline void sha256_compress(
//     uint32_t *__restrict state,
//     uint32_t *__restrict w)
// {
//     /*
//      * Expand W[16..63].
//      */
//     for (int i = 16; i < 64; ++i)
//     chess_prepare_for_pipelining
//     chess_loop_range(48, 48)
//     {
//         w[i] =
//             small_sigma1(w[i - 2]) +
//             w[i - 7] +
//             small_sigma0(w[i - 15]) +
//             w[i - 16];
//     }

//     uint32_t a = state[0];
//     uint32_t b = state[1];
//     uint32_t c = state[2];
//     uint32_t d = state[3];
//     uint32_t e = state[4];
//     uint32_t f = state[5];
//     uint32_t g = state[6];
//     uint32_t h = state[7];

//     /*
//      * SHA-256 has a strong loop-carried dependency.
//      * Do not force chess_prepare_for_pipelining here initially.
//      */
//     for (int i = 0; i < 64; ++i)
//     chess_loop_range(64, 64)
//     {
//         const uint32_t t1 =
//             h +
//             big_sigma1(e) +
//             choose(e, f, g) +
//             K[i] +
//             w[i];

//         const uint32_t t2 =
//             big_sigma0(a) +
//             majority(a, b, c);

//         h = g;
//         g = f;
//         f = e;
//         e = d + t1;
//         d = c;
//         c = b;
//         b = a;
//         a = t1 + t2;
//     }

//     state[0] += a;
//     state[1] += b;
//     state[2] += c;
//     state[3] += d;
//     state[4] += e;
//     state[5] += f;
//     state[6] += g;
//     state[7] += h;
// }

static inline void sha256_compress_fast(
    uint32_t *__restrict state,
    uint32_t *__restrict w)
{
    /*
     * Generate W[16..63], two words per iteration.
     */
    for (int i = 0; i < 48; i += 2)
    chess_prepare_for_pipelining
    chess_loop_range(24, 24)
    {
        const uint32_t w16 =
            w[i] +
            w[i + 9] +
            small_sigma0(w[i + 1]) +
            small_sigma1(w[i + 14]);

        w[i + 16] = w16;

        const uint32_t w17 =
            w[i + 1] +
            w[i + 10] +
            small_sigma0(w[i + 2]) +
            small_sigma1(w[i + 15]);

        w[i + 17] = w17;
    }

    uint32_t a = state[0];
    uint32_t b = state[1];
    uint32_t c = state[2];
    uint32_t d = state[3];
    uint32_t e = state[4];
    uint32_t f = state[5];
    uint32_t g = state[6];
    uint32_t h = state[7];

    /*
     * One SHA-256 round.
     *
     * The arguments are deliberately rotated by the caller.
     * Only d and h need to be updated in each invocation.
     */
#define SHA256_ROUND(A,B,C,D,E,F,G,H,WI,KI)            \
    do {                                               \
        const uint32_t _s1 =                           \
            rotr32((E), 6) ^                           \
            rotr32((E), 11) ^                          \
            rotr32((E), 25);                           \
                                                       \
        const uint32_t _ch =                           \
            (G) ^ ((E) & ((F) ^ (G)));                 \
                                                       \
        const uint32_t _t1 =                           \
            (H) + _s1 + _ch + (KI) + (WI);             \
                                                       \
        const uint32_t _s0 =                           \
            rotr32((A), 2) ^                           \
            rotr32((A), 13) ^                          \
            rotr32((A), 22);                           \
                                                       \
        const uint32_t _maj =                          \
            ((A) & (B)) ^                              \
            ((C) & ((A) ^ (B)));                       \
                                                       \
        const uint32_t _t2 = _s0 + _maj;               \
                                                       \
        (D) += _t1;                                    \
        (H)  = _t1 + _t2;                              \
    } while (0)

    /*
     * 64 rounds / 8 = 8 loop iterations.
     *
     * Register rotation is encoded in the argument order.
     */
    for (int i = 0; i < 64; i += 8)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        SHA256_ROUND(a,b,c,d,e,f,g,h, w[i + 0], K[i + 0]);
        SHA256_ROUND(h,a,b,c,d,e,f,g, w[i + 1], K[i + 1]);
        SHA256_ROUND(g,h,a,b,c,d,e,f, w[i + 2], K[i + 2]);
        SHA256_ROUND(f,g,h,a,b,c,d,e, w[i + 3], K[i + 3]);

        SHA256_ROUND(e,f,g,h,a,b,c,d, w[i + 4], K[i + 4]);
        SHA256_ROUND(d,e,f,g,h,a,b,c, w[i + 5], K[i + 5]);
        SHA256_ROUND(c,d,e,f,g,h,a,b, w[i + 6], K[i + 6]);
        SHA256_ROUND(b,c,d,e,f,g,h,a, w[i + 7], K[i + 7]);
    }

#undef SHA256_ROUND

    state[0] += a;
    state[1] += b;
    state[2] += c;
    state[3] += d;

    state[4] += e;
    state[5] += f;
    state[6] += g;
    state[7] += h;
}

#define SHA256_ROUND(A,B,C,D,E,F,G,H,WI,KI)          \
    do {                                             \
        const uint32_t _s1 =                         \
            rotr32((E), 6) ^                         \
            rotr32((E), 11) ^                        \
            rotr32((E), 25);                         \
                                                     \
        const uint32_t _ch =                         \
            (G) ^ ((E) & ((F) ^ (G)));               \
                                                     \
        const uint32_t _t1 =                         \
            (H) + _s1 + _ch + (KI) + (WI);           \
                                                     \
        const uint32_t _s0 =                         \
            rotr32((A), 2) ^                         \
            rotr32((A), 13) ^                        \
            rotr32((A), 22);                         \
                                                     \
        const uint32_t _maj =                        \
            ((A) & (B)) ^                            \
            ((C) & ((A) ^ (B)));                     \
                                                     \
        const uint32_t _t2 = _s0 + _maj;             \
                                                     \
        (D) += _t1;                                  \
        (H)  = _t1 + _t2;                            \
    } while (0)

#define SHA256_ROUND8(BASE)                                      \
    do {                                                         \
        SHA256_ROUND(a,b,c,d,e,f,g,h,                            \
                     w[(BASE)+0], K[(BASE)+0]);                   \
                                                                 \
        SHA256_ROUND(h,a,b,c,d,e,f,g,                            \
                     w[(BASE)+1], K[(BASE)+1]);                   \
                                                                 \
        SHA256_ROUND(g,h,a,b,c,d,e,f,                            \
                     w[(BASE)+2], K[(BASE)+2]);                   \
                                                                 \
        SHA256_ROUND(f,g,h,a,b,c,d,e,                            \
                     w[(BASE)+3], K[(BASE)+3]);                   \
                                                                 \
        SHA256_ROUND(e,f,g,h,a,b,c,d,                            \
                     w[(BASE)+4], K[(BASE)+4]);                   \
                                                                 \
        SHA256_ROUND(d,e,f,g,h,a,b,c,                            \
                     w[(BASE)+5], K[(BASE)+5]);                   \
                                                                 \
        SHA256_ROUND(c,d,e,f,g,h,a,b,                            \
                     w[(BASE)+6], K[(BASE)+6]);                   \
                                                                 \
        SHA256_ROUND(b,c,d,e,f,g,h,a,                            \
                     w[(BASE)+7], K[(BASE)+7]);                   \
    } while (0)

static inline void sha256_compress_full_unroll(
    uint32_t *__restrict state,
    uint32_t *__restrict w)
{
    /*
     * Keep the two-word message-schedule optimization first.
     */
    for (int i = 0; i < 48; i += 2)
    chess_prepare_for_pipelining
    chess_loop_range(24, 24)
    {
        const uint32_t w16 =
            w[i] +
            w[i + 9] +
            small_sigma0(w[i + 1]) +
            small_sigma1(w[i + 14]);

        w[i + 16] = w16;

        const uint32_t w17 =
            w[i + 1] +
            w[i + 10] +
            small_sigma0(w[i + 2]) +
            small_sigma1(w[i + 15]);

        w[i + 17] = w17;
    }

    uint32_t a = state[0];
    uint32_t b = state[1];
    uint32_t c = state[2];
    uint32_t d = state[3];

    uint32_t e = state[4];
    uint32_t f = state[5];
    uint32_t g = state[6];
    uint32_t h = state[7];

    /*
     * Fully unrolled 64 SHA-256 rounds.
     *
     * No runtime round loop.
     */
    SHA256_ROUND8(0);
    SHA256_ROUND8(8);
    SHA256_ROUND8(16);
    SHA256_ROUND8(24);

    SHA256_ROUND8(32);
    SHA256_ROUND8(40);
    SHA256_ROUND8(48);
    SHA256_ROUND8(56);

    state[0] += a;
    state[1] += b;
    state[2] += c;
    state[3] += d;

    state[4] += e;
    state[5] += f;
    state[6] += g;
    state[7] += h;
}
}


void trash0(
    input_stream<uint32_t> *__restrict input,
    output_stream<uint32_t> *__restrict output)
{
    /*
     * Input:
     *
     * data[8]
     * pub_seed[8]
     * addr[8]
     *
     * seed_state is assumed to be:
     *
     * Compress(
     *     IV,
     *     PRF_PREFIX || pub_seed
     * )
     */

    alignas(32) uint32_t data[8];
    alignas(32) uint32_t pub_seed[8];
    alignas(32) uint32_t addr[8];

    alignas(32) uint32_t w[64];

    /*
     * These should ideally be persistent across WOTS chain steps.
     */
    static uint32_t seed_state[8];
    static bool seed_state_valid = false;

    /*
     * ============================================================
     * Read packet
     * ============================================================
     */

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        data[i] = readincr(input);
    }

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        pub_seed[i] = readincr(input);
    }

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        addr[i] = readincr(input);
    }


    /*
     * ============================================================
     * Calculate common seeded state ONCE.
     *
     * This is valid only while pub_seed stays unchanged.
     * ============================================================
     */

    if (!seed_state_valid) {

        seed_state[0] = 0x6a09e667U;
        seed_state[1] = 0xbb67ae85U;
        seed_state[2] = 0x3c6ef372U;
        seed_state[3] = 0xa54ff53aU;
        seed_state[4] = 0x510e527fU;
        seed_state[5] = 0x9b05688cU;
        seed_state[6] = 0x1f83d9abU;
        seed_state[7] = 0x5be0cd19U;

        /*
         * PRF_PREFIX || pub_seed
         */
        w[0] = 0U;
        w[1] = 0U;
        w[2] = 0U;
        w[3] = 0U;
        w[4] = 0U;
        w[5] = 0U;
        w[6] = 0U;
        w[7] = 0x00000003U;

        for (int i = 0; i < 8; ++i)
        chess_prepare_for_pipelining
        chess_loop_range(8, 8)
        {
            w[8 + i] = pub_seed[i];
        }

        sha256_compress_full_unroll(
            seed_state,
            w
        );

        seed_state_valid = true;
    }


    /*
     * ============================================================
     * PRF
     *
     * state_prf = seed_state
     * ============================================================
     */

    uint32_t state_prf[8];

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        state_prf[i] = seed_state[i];
    }

    /*
     * addr(type = 0) || SHA padding
     */
    for (int i = 0; i < 7; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(7, 7)
    {
        w[i] = addr[i];
    }

    w[7]  = 0U;

    w[8]  = 0x80000000U;
    w[9]  = 0U;
    w[10] = 0U;
    w[11] = 0U;
    w[12] = 0U;
    w[13] = 0U;
    w[14] = 0U;
    w[15] = 0x00000300U;

    sha256_compress_full_unroll(
        state_prf,
        w
    );


    /*
     * ============================================================
     * IMPORTANT:
     *
     * Output PRF immediately.
     *
     * Final tile can start its Block 0 NOW, while this tile
     * computes MASK below.
     * ============================================================
     */

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        writeincr(output, state_prf[i]);
    }

    /*
     * Address needed by final node.
     *
     * Preserve original behavior:
     * final receives addr[7] = 0.
     */
    for (int i = 0; i < 7; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(7, 7)
    {
        writeincr(output, addr[i]);
    }

    writeincr(output, 0U);


    /*
     * ============================================================
     * MASK
     *
     * Start again from SAME precomputed seed state.
     * ============================================================
     */

    uint32_t state_mask[8];

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        state_mask[i] = seed_state[i];
    }


    /*
     * addr(type = 1) || padding
     */
    for (int i = 0; i < 7; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(7, 7)
    {
        w[i] = addr[i];
    }

    w[7]  = 1U;

    w[8]  = 0x80000000U;
    w[9]  = 0U;
    w[10] = 0U;
    w[11] = 0U;
    w[12] = 0U;
    w[13] = 0U;
    w[14] = 0U;
    w[15] = 0x00000300U;

    sha256_compress_full_unroll(
        state_mask,
        w
    );


    /*
     * ============================================================
     * MASK output
     *
     * digest XOR chain data
     * ============================================================
     */

    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        writeincr(
            output,
            state_mask[i] ^ data[i]
        );
    }


    /*
     * pub_seed for next WOTS chain step.
     */
    for (int i = 0; i < 8; ++i)
    chess_prepare_for_pipelining
    chess_loop_range(8, 8)
    {
        writeincr(output, pub_seed[i]);
    }
}